"""empty message

Revision ID: 1140c9492f1a
Revises: b3d657a8bc0d
Create Date: 2022-06-03 08:52:47.179596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1140c9492f1a'
down_revision = 'b3d657a8bc0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
