"""empty message

Revision ID: b3d657a8bc0d
Revises: 1e10cb9e68fa
Create Date: 2022-06-03 00:48:44.115136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3d657a8bc0d'
down_revision = '1e10cb9e68fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
